### ISSUE TITLE
Is the future import needed for anything?

### ISSUE THREAD

**Issue by runn1ng** [ajalt/python-sha1#3]
Hey,

a quick question... is the line

     from __future__ import print_function, unicode_literals

really needed for anything? It works without it for me and it doesn't confuse me with python3 unicode literals in python2 code

**Comment by ajalt** [comment]
You're right. Those imports were added as part of #1, which added Python3 support. The Unicode literals were never used, so I removed that import in 511c70d. The print function is used in the command line interface and the test file, so that was left in.
