### ISSUE TITLE
Getting hash of 1GB file under windows throws an error

### ISSUE THREAD

**Issue by sledgeh** [ajalt/python-sha1#4]
```
>sha1.py kali-2.0.1-rpi.img.xz
Traceback (most recent call last):
  File "D:\python-sha1\sha1.py", line 121, in <module>
    data = f.read()
MemoryError
```
I don't know what is problem but it has place to be. The size of `kali-2.0.1-rpi.img.xz` is 1038MB.

**Comment by ajalt** [comment]
Thanks for the bug report! A added support for arbitrary files in 6edf904a4, so this should work now. However, this code isn't designed for speed. On my computer, I can process about 0.5MiB/s, so it would take about an half an hour to process a 1GiB file.
